### ISSUE TITLE
Implement indenting: <<,>>,<,>

### ISSUE THREAD

**Issue by ev0rtex** [guillermooo/Six#14]
This one's literally been driving me crazy since switching to Six. I use line and block shifting constantly for indenting lines and selected blocks of text.

**Comment by guillermooo** [comment]
Me too. It's coming soon, I hope.

**Comment by ev0rtex** [comment]
@guillermooo I just saw that you closed this. I just tested and I had one additional question regarding it. Can you add support for a count modifier? I will often do e.g. '2>>' to indent multiple levels. Should this be added as a separate issue?

**Comment by guillermooo** [comment]
Here it's fine. I plan to polish all existing commands after Wave 1 is done during a Code Quality Cycle, but this oversight is too big. I'll try to fix it soon.

Feel free to report more issues as new issues too (which I will be more likely to see). If I close a feature it's normally because it's reached a functional level, not because it's completely finished. I hope to implement features to completion in successive iterations, not just in one go. But sometimes I may get too impatient and close an issue too prematurely like this one.
