### ISSUE TITLE
multiple selection behave differently in normal and insert model

### ISSUE THREAD

**Issue by edhub** [guillermooo/Six#196]
In insert model, cmd + D only select the word
In normal model, cmd + D selects the word + space after it

Every time I do multiple selection in normal model, I have to press esc to cancel the selection, and then edit.

**Comment by guillermooo** [comment]
When in normal mode, you should use `gh` or `gH` for entering multiple [line] selection mode, then use `j` for adding selections, `k` for removing selections and `l` for skipping the current selection.

Note that you cannot perform operations directly while in any of the two selection modes. You first have to press `Esc` or `v`. This may change in the future so that operations can be done directly in multiple selection mode, but there are no immediate plans for this.

**Comment by edhub** [comment]
thanks for the reply 👍
